<a href="https://colab.research.google.com/github/Simran085/ML_LAB_ASS_102216115/blob/main/A6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Q1.	(Gaussian Naïve Bayes Classifier) Implement Gaussian Naïve Bayes Classifier on the Iris dataset from sklearn.datasets using
       # (i) Step-by-step implementation
       # (ii) In-built function

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving iris.data.csv to iris.data.csv


In [ ]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load Iris dataset
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Target classes (0, 1, 2)

# Train-Test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 1: Calculate the mean and variance for each feature per class
classes = np.unique(y_train)
means = {}
variances = {}
priors = {}

for cls in classes:
    X_class = X_train[y_train == cls]
    means[cls] = np.mean(X_class, axis=0)
    variances[cls] = np.var(X_class, axis=0)
    priors[cls] = X_class.shape[0] / X_train.shape[0]

# Step 2: Gaussian Probability Density Function
def gaussian_pdf(x, mean, var):
    exponent = np.exp(-((x - mean) ** 2) / (2 * var))
    return (1 / np.sqrt(2 * np.pi * var)) * exponent

# Step 3: Classify based on likelihood and prior
def predict(X):
    predictions = []
    for sample in X:
        posteriors = []
        for cls in classes:
            prior = np.log(priors[cls])  # log of prior
            likelihood = np.sum(np.log(gaussian_pdf(sample, means[cls], variances[cls])))  # log of likelihood
            posterior = prior + likelihood
            posteriors.append(posterior)
        predictions.append(np.argmax(posteriors))
    return np.array(predictions)

# Make predictions on the test set
y_pred_step_by_step = predict(X_test)

# Evaluate
print("Step-by-step Gaussian Naive Bayes Implementation:")
print("Accuracy:", accuracy_score(y_test, y_pred_step_by_step))
print("\nClassification Report:\n", classification_report(y_test, y_pred_step_by_step))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_step_by_step))


Step-by-step Gaussian Naive Bayes Implementation:
Accuracy: 0.9777777777777777

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45


Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
