<a href="https://colab.research.google.com/github/Simran085/ML_LAB_ASS_102216115/blob/main/ML_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Q1: a. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

import numpy as np
arr = np.array([1,2,3,4,5])
n = len(a)
rev = arr[::-1]    #[start: stop: step]
print("Reverse Matrix:")
print(rev)

Reverse Matrix:
[5 4 3 2 1]


In [ ]:
# Q1.b. Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods

# M1
import numpy as np
arr = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flatten_arr = arr.ravel()
print(flatten_arr)

#M2
import numpy as np
arr1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flatten_arr1 = arr1.ravel()
print(flatten_arr1)


[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [ ]:
# Q1.c. Compare the following numpy arrays:

import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(arr1 == arr2)


[[ True  True]
 [ True  True]]


In [ ]:
# Q4.d.  (i)  Find the most frequent value and their indice(s)

import numpy as np
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
most_frequent_val = np.bincount(x).argmax()
indices = np.where(x == most_frequent_val)[0]
print(most_frequent_val)
print(indices)

#(ii)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_frequent_val_y = np.bincount(y).argmax()
indices_y = np.where(y == most_frequent_val_y)[0]
print(most_frequent_val)
print(indices_y)

1
[0 5 7 8 9]
1
[0 1 2]


In [ ]:
# Q1.e. (i) Sum of all elements, (ii) Sum of all elements row-wise (iii) Sum of all elements column-wise

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
total_sum = gfg.sum()
row_sum = gfg.sum(axis = 1)
col_sum = gfg.sum(axis = 0)

print(total_sum)
print(row_sum)
print(col_sum)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [ ]:
#Q.1.f.

arr = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

# i. Sum of diagonal elements
diagonal_sum = np.trace(arr)

# ii. Eigenvalues of the matrix
eigenvalues = np.linalg.eigvals(arr)

# iii. Eigenvectors of the matrix
eigenvalues, eigenvectors = np.linalg.eig(arr)

# iv. Inverse of the matrix
inverse_matrix = np.linalg.inv(arr)

# v. Determinant of the matrix
determinant = np.linalg.det(arr)

print(diagonal_sum)
print(eigenvalues)
print(eigenvectors)
print(inverse_matrix)
print(determinant)

176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [ ]:
# Q1.g. Multiply the following matrices and also find covariance between matrices
# (i)
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
product = np.dot(p, q)
print("Matrix Product:")
print(product)

# for covariance: flatten the matrix
p_flat = p.flatten()
q_flat = q.flatten()

mean_p = np.mean(p_flat)
mean_q = np.mean(q_flat)

cov_matrix = np.sum((p_flat - mean_p) * (q_flat - mean_q)) / (len(p_flat) - 1)
print("Covariance matrix: ")
print(cov_matrix)


Matrix Product:
[[16 19]
 [26 31]]
Covariance matrix: 
[[0.66666667 1.        ]
 [1.         1.66666667]]


In [ ]:
#(ii)

p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
product = np.dot(p,q)
print("Matrix Product: ")
print(product)

# finding covariance
p_flat = p.flatten()
q_flat = q.flatten()

mean_p = np.mean(p_flat)
mean_q = np.mean(q_flat)

cov_matrix = np.sum((p_flat - mean_p) * (q_flat - mean_q)) / (len(p_flat) - 1)
print("Covariance matrix: ")
print(cov_matrix)


Matrix Product: 
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix: 
0.23333333333333356


In [ ]:
# Q1.h.  For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]), find inner, outer and cartesian product?

import numpy as np
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner_product = np.inner(x,y)
print("Inner Product: ")
print(inner_product)

outer_product = np.outer(x,y)
print("Outer Product: ")
print(outer_product)

x_flat = x.flatten()
y_flat = y.flatten()
cartesian_product = np.array(np.meshgrid(x_flat,y_flat)).T.reshape(-1,2)
print("Cartesian Product: ")
print(cartesian_product)


Inner Product: 
[[17 52]
 [13 62]]
Outer Product: 
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian Product: 
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
# Q2.a. (i)For the array: array = np.array([[1, -2, 3],[-4, 5, -6]]) i. Find element-wise absolute value

import numpy as np
arr = np.array([[1, -2, 3],[-4, 5, -6]])
abs_values = np.abs(arr)
print("Element-wise absolute values: ")
print(abs_values)


Element-wise absolute values: 
[[1 2 3]
 [4 5 6]]


In [ ]:
# ii. Percentiles of flattened array, for each column, and for each row

import numpy as np
arr = np.array([[1, -2, 3],[-4, 5, -6]])

flattened_arr = arr.flatten()
percentiles_flat = np.percentile(flattened_arr, [25,50,75])
print("25th, 50th, 75th percentiles of flattened array: ")
print(percentiles_flat)

percentiles_col  = np.percentile(arr, [25,50,75], axis = 0)
print("25th, 50th, 75th percentiles for each column: ")
print(percentiles_col)

percentiles_row  = np.percentile(arr, [25,50,75], axis = 1)
print("25th, 50th, 75th percentiles for each row: ")
print(percentiles_row)


25th, 50th, 75th percentiles of flattened array: 
[-3.5 -0.5  2.5]
25th, 50th, 75th percentiles for each column: 
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
25th, 50th, 75th percentiles for each row: 
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [ ]:
# iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row

# Flattened arr
mean_flat = np.mean(flattened_arr)
median_flat = np.median(flattened_arr)
std_flat = np.std(flattened_arr)
print("Mean, Median, Standard deviation of flattened arr: ")
print(mean_flat, median_flat, std_flat)

# For each col
mean_col = np.mean(arr, axis = 0)
median_col = np.median(arr, axis = 0)
std_col = np.std(arr, axis = 0)
print("Mean, Median, Standard deviation of each col: ")
print(mean_col, median_col, std_col)

#For each row
mean_row = np.mean(arr, axis = 1)
median_row = np.median(arr, axis = 1)
std_row = np.std(arr, axis = 1)
print("Mean, Median, Standard deviation of each row: ")
print(mean_row, median_row, std_row)


Mean, Median, Standard deviation of flattened arr: 
-0.5 -0.5 3.8622100754188224
Mean, Median, Standard deviation of each col: 
[-1.5  1.5 -1.5] [-1.5  1.5 -1.5] [2.5 3.5 4.5]
Mean, Median, Standard deviation of each row: 
[ 0.66666667 -1.66666667] [ 1. -4.] [2.05480467 4.78423336]


In [ ]:
# Q2. b. For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling and truncated value, rounded values

a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
floor_values = np.floor(a)
ceil_values = np.ceil(a)
trunc_values = np.trunc(a)
round_values = np.round(a)

print("Floor values: ")
print(floor_values)

print("Ceiling values: ")
print(ceil_values)

print("Truncated values: ")
print(trunc_values)

print("Rounded values: ")
print(round_values)

Floor values: 
[-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: 
[-1. -1. -0.  1.  2.  2.  3.]
Truncated values: 
[-1. -1. -0.  0.  1.  1.  3.]
Rounded values: 
[-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
# Q3.a. (i)For the array: array = np.array([10, 52, 62, 16, 16, 54, 453])

import numpy as np
arr = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_arr = np.sort(arr)
print("Sorted arr: ", sorted_arr)

# ii. Indices of sorted array
indices_sorted_arr = np.argsort(arr)
print("Indices of sorted arr: ", indices_sorted_arr)

# iii.  4 smallest elements
smallest_elements = np.sort(arr)[:4]
print("4 smallest elements: ", smallest_elements)

# iv. 5 largest elements
largest_elements = np.sort(arr)[-5:]
print("5 largest elements: ", largest_elements)


Sorted arr:  [ 10  16  16  52  54  62 453]
Indices of sorted arr:  [0 3 4 1 5 2 6]
4 smallest elements:  [10 16 16 52]
5 largest elements:  [ 16  52  54  62 453]


In [ ]:
# Q3.b.  For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

import numpy as np
arr = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# (i) Integer elements only
integer_ele = arr[arr == arr.astype(int)]
print("Integer elements only: ", integer_ele)

# (ii) Float elements only
float_ele = arr[arr != arr.astype(int)]
print("Float elements only: ", float_ele)


Integer elements only:  [1. 2. 3. 2.]
Float elements only:  [1.2 2.2]
